name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: Set up multipass
        run: sudo snap install multipass --classic

      - name: Build
        run: snapcraft
